import type {
  Contact, Company, HuntSession, WorkspaceMember, WorkspaceStats,
  ApolloCredits, SavedList, WebhookPending, XRayResult, HubSpotSyncResult,
} from "./types";

// ─── Apollo Credits ──────────────────────────────────────────────────────────

export const mockApolloCredits: ApolloCredits = {
  export_used: 847,
  export_total: 1000,
  phone_used: 43,
  phone_total: 100,
};

// ─── Contacts (com campos Apollo + HubSpot) ──────────────────────────────────

export const mockContacts: Contact[] = [
  {
    id: "c-001",
    nome_original: "RAFAEL COSTA MENDONCA",
    nome_nutrido: "Rafael Costa Mendonça",
    empresa_original: "TOTVS SA",
    empresa_nutrido: "TOTVS S.A.",
    cargo_original: "DIRETOR TI",
    cargo_nutrido: "Chief Technology Officer",
    email_original: "r.mendonca@totvs.com.br",
    email_nutrido: "rafael.mendonca@totvs.com.br",
    telefone_original: "+5511999887766",
    telefone_nutrido: "+55 (11) 99988-7766",
    email_status: "valid",
    seniority_level: "c-level",
    industry: "Enterprise Software / ERP",
    apollo_id: "apo_6d3f1a2b",
    phone_status: "received",
    linkedin_profile_url: "linkedin.com/in/rafaelmendonca",
    hubspot_id: "58210934",
    hubspot_synced: true,
    hubspot_action: "updated_by_id",
    tempo_no_cargo: "2 anos e 4 meses",
    status_contato: "high_intent",
    tokens_spent: 12,
    ultima_atualizacao: "2026-05-10",
    mudanca_recente: "Assumiu nova liderança há 3 meses",
    score: 94,
    fonte: "extension",
    import_method: "extension",
  },
  {
    id: "c-002",
    nome_original: "PATRICIA LIMA SOUZA",
    nome_nutrido: "Patrícia Lima Souza",
    empresa_original: "AMBEV SA",
    empresa_nutrido: "AmBev S.A.",
    cargo_original: "VP MARKETING",
    cargo_nutrido: "VP de Marketing & Growth",
    email_original: "p.souza@ambev.com.br",
    email_nutrido: "patricia.lima@ambev.com.br",
    telefone_original: "+5511988776655",
    telefone_nutrido: "+55 (11) 98877-6655",
    email_status: "valid",
    seniority_level: "director",
    industry: "Beverages / FMCG",
    apollo_id: "apo_7c4e2b3a",
    phone_status: "received",
    linkedin_profile_url: "linkedin.com/in/patricialima",
    hubspot_id: "58210935",
    hubspot_synced: true,
    hubspot_action: "created",
    tempo_no_cargo: "1 ano e 8 meses",
    status_contato: "high_intent",
    tokens_spent: 15,
    ultima_atualizacao: "2026-05-12",
    mudanca_recente: "Empresa em expansão — abriu 3 vagas sênior",
    score: 88,
    fonte: "extension",
    import_method: "extension",
  },
  {
    id: "c-003",
    nome_original: "MARCOS AUGUSTO FREITAS",
    nome_nutrido: "Marcos Augusto Freitas",
    empresa_original: "BANCO ITAU UNIBANCO",
    empresa_nutrido: "Itaú Unibanco S.A.",
    cargo_original: "GERENTE PRODUTOS DIGITAIS",
    cargo_nutrido: "Head de Produtos Digitais",
    email_original: "m.freitas@itau.com.br",
    email_nutrido: "marcos.freitas@itau-unibanco.com.br",
    telefone_original: "+5511977665544",
    email_status: "risky",
    seniority_level: "manager",
    industry: "Financial Services / Banking",
    apollo_id: "apo_5a3d1c2e",
    phone_status: "pending",
    linkedin_profile_url: "linkedin.com/in/marcosfreitas",
    hubspot_synced: false,
    tempo_no_cargo: "3 anos e 1 mês",
    status_contato: "medium_intent",
    tokens_spent: 8,
    ultima_atualizacao: "2026-05-08",
    score: 72,
    fonte: "extension",
    import_method: "text",
  },
  {
    id: "c-004",
    nome_original: "FERNANDA OLIVEIRA CASTRO",
    nome_nutrido: "Fernanda Oliveira Castro",
    empresa_original: "ROCK CONTENT LTDA",
    empresa_nutrido: "Rock Content",
    cargo_original: "CMO",
    cargo_nutrido: "Chief Marketing Officer",
    email_original: "f.castro@rockcontent.com",
    email_nutrido: "fernanda.castro@rockcontent.com",
    email_status: "valid",
    seniority_level: "c-level",
    industry: "Content Marketing / SaaS",
    apollo_id: "apo_2b1f3e4a",
    phone_status: "not_found",
    linkedin_profile_url: "linkedin.com/in/fernandacastro",
    hubspot_id: "58210940",
    hubspot_synced: true,
    hubspot_action: "created",
    tempo_no_cargo: "4 anos e 6 meses",
    status_contato: "medium_intent",
    tokens_spent: 10,
    ultima_atualizacao: "2026-05-11",
    score: 65,
    fonte: "xray",
    import_method: "extension",
  },
  {
    id: "c-005",
    nome_original: "THIAGO MENDES RODRIGUES",
    nome_nutrido: "Thiago Mendes Rodrigues",
    empresa_original: "VTEX COMMERCE LTDA",
    empresa_nutrido: "VTEX",
    cargo_original: "CTO",
    cargo_nutrido: "Chief Technology Officer",
    email_original: "t.rodrigues@vtex.com",
    email_nutrido: "thiago.rodrigues@vtex.com",
    telefone_original: "+5521977884455",
    telefone_nutrido: "+55 (21) 97788-4455",
    email_status: "valid",
    seniority_level: "c-level",
    industry: "E-commerce / Commerce SaaS",
    apollo_id: "apo_9e8d7c6b",
    phone_status: "received",
    linkedin_profile_url: "linkedin.com/in/thiagomendes",
    hubspot_id: "58210941",
    hubspot_synced: true,
    hubspot_action: "updated_by_email",
    tempo_no_cargo: "5 anos e 2 meses",
    status_contato: "high_intent",
    tokens_spent: 18,
    ultima_atualizacao: "2026-05-14",
    mudanca_recente: "VTEX levantou rodada Série D — R$ 240M",
    score: 97,
    fonte: "extension",
    import_method: "extension",
  },
  {
    id: "c-006",
    nome_original: "CAROLINA SANTOS NEVES",
    nome_nutrido: "Carolina Santos Neves",
    empresa_original: "LINX SISTEMAS",
    empresa_nutrido: "Linx (Stone Co.)",
    cargo_original: "DIRETORA COMERCIAL",
    cargo_nutrido: "Diretora de Vendas Enterprise",
    email_original: "c.neves@linx.com.br",
    email_status: "unknown",
    seniority_level: "director",
    industry: "Retail Tech / POS",
    apollo_id: "apo_3a2b1c4d",
    phone_status: "not_found",
    linkedin_profile_url: "linkedin.com/in/carolinaneves",
    hubspot_synced: false,
    tempo_no_cargo: "1 ano e 1 mês",
    status_contato: "low_intent",
    tokens_spent: 6,
    ultima_atualizacao: "2026-05-05",
    score: 41,
    fonte: "xray",
    import_method: "text",
  },
  {
    id: "c-007",
    nome_original: "BRUNO HENRIQUE ROCHA",
    nome_nutrido: "Bruno Henrique Rocha",
    empresa_original: "RD STATION",
    empresa_nutrido: "RD Station (TOTVS Group)",
    cargo_original: "HEAD ENGENHARIA",
    cargo_nutrido: "Head de Engenharia de Software",
    email_original: "b.rocha@rdstation.com",
    email_nutrido: "bruno.rocha@rdstation.com",
    email_status: "valid",
    seniority_level: "manager",
    industry: "Marketing Automation / SaaS",
    apollo_id: "apo_4f5e6d7c",
    phone_status: "pending",
    linkedin_profile_url: "linkedin.com/in/brunohrocha",
    hubspot_synced: false,
    tempo_no_cargo: "2 anos e 7 meses",
    status_contato: "medium_intent",
    tokens_spent: 9,
    ultima_atualizacao: "2026-05-13",
    score: 76,
    fonte: "extension",
    import_method: "extension",
  },
  {
    id: "c-008",
    nome_original: "JULIA MENDES CASTRO",
    nome_nutrido: "Júlia Mendes Castro",
    empresa_original: "PIPEFY INC",
    empresa_nutrido: "Pipefy",
    cargo_original: "CMO",
    cargo_nutrido: "Chief Marketing Officer",
    email_original: "j.castro@pipefy.com",
    email_nutrido: "julia.castro@pipefy.com",
    telefone_original: "+5541988776655",
    telefone_nutrido: "+55 (41) 98877-6655",
    email_status: "valid",
    seniority_level: "c-level",
    industry: "BPM / Workflow Automation SaaS",
    apollo_id: "apo_8g7h6i5j",
    phone_status: "received",
    linkedin_profile_url: "linkedin.com/in/juliamendes",
    hubspot_id: "58210944",
    hubspot_synced: true,
    hubspot_action: "created",
    tempo_no_cargo: "3 anos e 3 meses",
    status_contato: "high_intent",
    tokens_spent: 14,
    ultima_atualizacao: "2026-05-15",
    score: 91,
    fonte: "extension",
    import_method: "extension",
  },
];

// ─── Company ──────────────────────────────────────────────────────────────────

export const mockCompany: Company = {
  id: "co-001",
  razao_social: "VTEX COMMERCE SOLUTIONS LTDA",
  nome_fantasia: "VTEX",
  cnpj: "05.314.972/0001-74",
  cnae_principal: "6201-5/01",
  cnae_descricao: "Desenvolvimento de programas de computador sob encomenda",
  brand_sector: "Plataforma de Commerce Digital SaaS — infraestrutura para varejistas enterprise operarem loja virtual, OMS e marketplace em uma única stack headless",
  faturamento_estimado: "R$ 1.2B – 1.8B",
  valuation: "USD 1.7B (Série D, 2024)",
  funcionarios: 1800,
  cidade: "Rio de Janeiro",
  estado: "RJ",
  website: "vtex.com",
  impacto_mercado: "Líder em commerce B2B/B2C para LATAM e Europa. Clientes incluem Coca-Cola, Walmart, Loreal e AB InBev. Crescimento de 40% YoY em ARR.",
  serasa_score: 820,
  status_receita: "ativa",
  data_abertura: "2000-02-20",
  c_levels: [
    { nome: "Geraldo Thomaz", cargo: "Co-CEO", linkedin: "linkedin.com/in/geraldothomazjr", tempo_empresa: "24 anos" },
    { nome: "Mariano Gomide de Faria", cargo: "Co-CEO", linkedin: "linkedin.com/in/marianogomide", tempo_empresa: "24 anos" },
    { nome: "Ricardo Camatta", cargo: "CFO", linkedin: "linkedin.com/in/ricardocamatta", tempo_empresa: "8 anos" },
    { nome: "Thiago Mendes Rodrigues", cargo: "CTO", linkedin: "linkedin.com/in/thiagomendes", tempo_empresa: "5 anos" },
    { nome: "Alexandre Soncini", cargo: "CMO", linkedin: "linkedin.com/in/alexandresoncini", tempo_empresa: "3 anos" },
  ],
};

// ─── Hunt Sessions ────────────────────────────────────────────────────────────

export const mockHuntSessions: HuntSession[] = [
  {
    id: "h-001",
    nome: "CTOs SaaS B2B — SP/RJ",
    status: "completed",
    fontes: ["extension", "linkedin"],
    contatos_encontrados: 143,
    tokens_consumidos: 1716,
    progresso: 100,
    criado_em: "2026-05-13T09:00:00",
    concluido_em: "2026-05-13T09:47:00",
    filtros: { cargos: ["CTO", "VP de Tecnologia"], localizacoes: ["São Paulo", "Rio de Janeiro"], cnaes: ["6201-5/01"] },
  },
  {
    id: "h-002",
    nome: "Diretores Financeiros — Varejo Nacional",
    status: "running",
    fontes: ["serasa", "extension"],
    contatos_encontrados: 67,
    tokens_consumidos: 804,
    progresso: 47,
    criado_em: "2026-05-15T08:30:00",
    filtros: { cargos: ["CFO", "Diretor Financeiro"], localizacoes: ["Brasil"], cnaes: ["4711-3/02"] },
  },
  {
    id: "h-003",
    nome: "CMOs Fintech — X-Ray LinkedIn",
    status: "scheduled",
    fontes: ["xray"],
    contatos_encontrados: 0,
    tokens_consumidos: 0,
    progresso: 0,
    criado_em: "2026-05-15T10:00:00",
    filtros: { cargos: ["CMO", "VP de Marketing"], localizacoes: ["São Paulo"], cnaes: ["6491-3/00"] },
  },
];

// ─── Saved Lists ──────────────────────────────────────────────────────────────

export const mockSavedLists: SavedList[] = [
  {
    id: "list-001",
    name: "Diretores Mkt Tech SP — Maio 2026",
    total_profiles: 50,
    enriched_count: 45,
    valid_emails: 38,
    created_at: "2026-05-13T09:00:00",
    updated_at: "2026-05-13T10:15:00",
    username: "Yago Barbosa",
    storage: "gcs",
    sources: ["extension"],
  },
  {
    id: "list-002",
    name: "CTOs SaaS — SP/RJ Q2",
    total_profiles: 143,
    enriched_count: 143,
    valid_emails: 119,
    created_at: "2026-05-10T14:30:00",
    updated_at: "2026-05-10T15:22:00",
    username: "Yago Barbosa",
    storage: "gcs",
    sources: ["extension", "xray"],
  },
  {
    id: "list-003",
    name: "Fintech RJ — Abordagem Inicial",
    total_profiles: 28,
    enriched_count: 20,
    valid_emails: 17,
    created_at: "2026-05-08T11:00:00",
    updated_at: "2026-05-08T11:45:00",
    username: "Ana Rodrigues",
    storage: "local",
    sources: ["xray", "text"],
  },
  {
    id: "list-004",
    name: "Logística SP — HTML Import",
    total_profiles: 35,
    enriched_count: 0,
    valid_emails: 0,
    created_at: "2026-05-06T09:00:00",
    updated_at: "2026-05-06T09:00:00",
    username: "Carlos Mendes",
    storage: "local",
    sources: ["html"],
  },
];

// ─── Webhooks Pending ─────────────────────────────────────────────────────────

export const mockWebhooksPending: WebhookPending[] = [
  { apollo_id: "apo_5a3d1c2e", contact_name: "Marcos Augusto Freitas", requested_at: "2026-05-15T10:02:00", status: "pending" },
  { apollo_id: "apo_4f5e6d7c", contact_name: "Bruno Henrique Rocha", requested_at: "2026-05-15T10:02:10", status: "pending" },
];

// ─── X-Ray Results (mock) ─────────────────────────────────────────────────────

export const mockXRayResults: XRayResult[] = [
  { id: "xr-001", nome: "André Camargo", linkedin_url: "linkedin.com/in/andrecamargo", titulo: "Head of Engineering", empresa: "iFood", snippet: "Head of Engineering @ iFood · 6 years leading backend infra teams in São Paulo...", tags: ["engineering", "backend", "foodtech"] },
  { id: "xr-002", nome: "Letícia Brandão", linkedin_url: "linkedin.com/in/leticiabrandao", titulo: "Director of Technology", empresa: "Loggi", snippet: "Director of Technology at Loggi. Scaling last-mile delivery infrastructure...", tags: ["logistics", "director", "tech"] },
  { id: "xr-003", nome: "Rodrigo Fonseca", linkedin_url: "linkedin.com/in/rodrigofonseca", titulo: "VP Engineering", empresa: "Neon Bank", snippet: "VP of Engineering @ Neon. Digital bank infrastructure, 200+ engineers...", tags: ["fintech", "vp", "banking"] },
  { id: "xr-004", nome: "Marina Alves", linkedin_url: "linkedin.com/in/marinaalves", titulo: "CTO", empresa: "Omie", snippet: "CTO at Omie ERP. SMB cloud ERP for Brazilian businesses...", tags: ["erp", "cto", "smb"] },
  { id: "xr-005", nome: "Felipe Guimarães", linkedin_url: "linkedin.com/in/felipeguimaraes", titulo: "Diretor de TI", empresa: "Magazine Luiza", snippet: "Diretor de Tecnologia da Informação — Magazine Luiza. Retail tech transformation...", tags: ["retail", "ti", "director"] },
];

// ─── HubSpot Sync Result ──────────────────────────────────────────────────────

export const mockHubSpotSyncResult: HubSpotSyncResult = {
  total: 6,
  created: 3,
  updated: 2,
  failed: 0,
  skipped: 1,
  http_status: 207,
  decisions: [
    { contact_id: "c-001", nome: "Rafael Costa Mendonça", email: "rafael.mendonca@totvs.com.br", action: "updated_by_id", hubspot_id: "58210934" },
    { contact_id: "c-002", nome: "Patrícia Lima Souza", email: "patricia.lima@ambev.com.br", action: "created", hubspot_id: "58210935" },
    { contact_id: "c-004", nome: "Fernanda Oliveira Castro", email: "fernanda.castro@rockcontent.com", action: "created", hubspot_id: "58210940" },
    { contact_id: "c-005", nome: "Thiago Mendes Rodrigues", email: "thiago.rodrigues@vtex.com", action: "updated_by_email", hubspot_id: "58210941" },
    { contact_id: "c-008", nome: "Júlia Mendes Castro", email: "julia.castro@pipefy.com", action: "created", hubspot_id: "58210944" },
    { contact_id: "c-006", nome: "Carolina Santos Neves", email: undefined, action: "skipped" },
  ],
};

// ─── Team Members ─────────────────────────────────────────────────────────────

export const mockTeamMembers: WorkspaceMember[] = [
  { id: "u-001", nome: "Yago Barbosa", username: "yago", email: "yago@vero.io", role: "admin", avatar_color: "#8A5CF5", tokens_quota: 10000, tokens_used: 4280, ultimo_acesso: "Agora", status: "active", created_at: "2026-01-10" },
  { id: "u-002", nome: "Ana Rodrigues", username: "ana", email: "ana@vero.io", role: "member", avatar_color: "#10B981", tokens_quota: 3000, tokens_used: 1850, ultimo_acesso: "há 2h", status: "active", created_at: "2026-02-14" },
  { id: "u-003", nome: "Carlos Mendes", username: "carlos", email: "carlos@vero.io", role: "member", avatar_color: "#F59E0B", tokens_quota: 3000, tokens_used: 620, ultimo_acesso: "há 1d", status: "active", created_at: "2026-03-01" },
  { id: "u-004", nome: "Beatriz Costa", username: "beatriz", email: "beatriz@vero.io", role: "member", avatar_color: "#EC4899", tokens_quota: 500, tokens_used: 0, ultimo_acesso: "Nunca", status: "invited", created_at: "2026-05-14" },
];

// ─── Workspace Stats ──────────────────────────────────────────────────────────

export const mockWorkspaceStats: WorkspaceStats = {
  total_contacts: 1847,
  total_companies: 312,
  active_hunts: 1,
  tokens_used_month: 6750,
  tokens_quota_month: 16500,
  enrichment_rate: 89.3,
  sources_active: 4,
  emails_found: 1640,
  emails_valid: 1312,
  unique_companies: 287,
  unique_titles: 94,
  hubspot_synced: 1284,
};
